name: additional_hooks
description: Bunch of hooks for your app when you are using the flutter-hooks package.
version: 0.0.1
author: Boris Kayi
homepage: https://github.com/silverhairs/additional_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flutter_hooks: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
